apiVersion: apps/v1
kind: Deployment
metadata:
  name: abcelectronics
  labels:
    app: abcelectronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abcelectronics
  template:
    metadata:
      labels:
        app: abcelectronics
    spec:
      containers:
      - name: abcelectronics
        image: komal1309/sprintelectronics
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: abcelectronics
spec:
  type: LoadBalancer
  selector:
    app: abcelectronics
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080