# spring:
#   datasource:
#     driver-class-name: org.postgresql.Driver
#     platform: postgresql
#     url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}?useSSL=false
#     username: {POSTGRES_USER}
#     password: {POSTGRES_PASSWORD}

#   jpa:
#     database-platform: org.hibernate.dialect.PostgresPlusDialect
#     generate-ddl: true
#     show-sql: true
#     hibernate:
#       ddl-auto: update